### ISSUE TITLE
HttpException: "Server cannot set status after HTTP headers have been sent."

### ISSUE THREAD

**Issue by anjdreas** [devbridge/AzurePowerTools#6]
I get this exception every time I visit the website unauthenticated, just priori to being shown the basic auth dialog in the browser. It all works, but it seems to me that there is a bug that the headers are manipulated too late in the ASP.net pipeline?

```
System.Web.HttpException was unhandled by user code
  ErrorCode=-2147467259
  HResult=-2147467259
  Message=Server cannot set status after HTTP headers have been sent.
  Source=System.Web
  WebEventCode=0
  StackTrace:
       at System.Web.HttpResponse.set_StatusCode(Int32 value)
       at Devbridge.BasicAuthentication.BasicAuthenticationModule.IssueAuthenticationChallenge(Object source, EventArgs e) in c:\Repos\Foo\Modules\BasicAuth\BasicAuthenticationModule.cs:line 138
       at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
       at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
  InnerException: 
```

**Comment by bradgyton** [comment]
Did you resolve this at all?

**Comment by anjdreas** [comment]
No, but I haven't really faced this issue since so I am closing it.
